config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :users
  #root route
  root to: redirect('/home', status:302)

  #homepage
  get 'home', to: 'static_pages#home', as: 'home'
  get 'about', to: 'static_pages#about', as: 'about'

  # requests
  get 'requests', to: 'requests#index', as: 'requests' # index
  get 'requests/new', to: 'requests#new', as: 'new_request' # new
  post 'requests', to: 'requests#create' # create
  get 'requests/:id', to: 'requests#show', as: 'request' # show
  get 'requests/:id/edit', to: 'requests#edit', as: 'edit_request' # edit
  patch 'requests/:id', to: 'requests#update' # update (as needed)
  put 'requests/:id', to: 'requests#update' # update (full replacement)
  delete 'requests/:id', to: 'requests#destroy' # destroy

  # messages
  get 'messages', to: 'messages#index', as: 'messages' # index
  get 'messages/new', to: 'messages#new', as: 'new_message' # new
  post 'messages', to: 'messages#create' # create
  get 'messages/:id', to: 'messages#show', as: 'message' # show
  get 'messages/:id/edit', to: 'messages#edit', as: 'edit_message' # edit
  patch 'messages/:id', to: 'messages#update' # update (as needed)
  put 'messages/:id', to: 'messages#update' # update (full replacement)
  delete 'messages/:id', to: 'messages#destroy' # destroy


# globals
get 'globals', to: 'globals#index', as: 'globals' # index
get 'globals/new', to: 'globals#new', as: 'new_global' # new
post 'globals', to: 'globals#create' # create
get 'globals/:id', to: 'globals#show', as: 'global' # show
get 'globals/:id/edit', to: 'globals#edit', as: 'edit_global' # edit
patch 'globals/:id', to: 'globals#update' # update (as needed)
put 'globals/:id', to: 'globals#update' # update (full replacement)
delete 'globals/:id', to: 'globals#destroy' # destroy

#global_listings
get 'global_listings', to: 'global_listings#index', as: 'global_listings' # index
get 'global_listings/new', to: 'global_listings#new', as: 'new_global_global_listings' # new
post 'global_listings', to: 'global_listings#create' # create
get 'global_listings/:id', to: 'global_listings#show', as: 'global_listing' # show
get 'global_listings/:id/edit', to: 'global_listings#edit', as: 'edit_global_listing' # edit
patch 'global_listings/:id', to: 'global_listings#update' # update (as needed)
put 'global_listings/:id', to: 'global_listings#update' # update (full replacement)
delete 'global_listings/:id', to: 'global_listings#destroy' # destroy

  # users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'users/:id', to: 'users#show', as: 'user'

  get 'profile', to: 'static_pages#profile', as: 'profile'
  get 'users', to: 'users#index', as: 'users'

  

  # videos
  get 'account/videos', to: 'account_videos#index', as: 'account_videos' # index

  get 'account/videos/new', to: 'account_videos#new', as: 'new_account_video' # new
  post 'account/videos', to: 'account_videos#create' # create

  get '/videos/:id', to: 'videos#show', as: 'video' # show

  get 'videos/:id/edit', to: 'videos#edit', as: 'edit_video' #edit
  patch 'videos/:id', to: 'videos#update' # update
  put 'videos/:id', to: 'videos#update' # update

  delete 'videos/:id', to: 'videos#destroy' # delete


  #my_notifications
  resources :my_notifications do
    collection do 
      post :mark_as_read
    end
  end

  delete "my_notifications/:id", to: "my_notifications#destroy"  # delete
    
  # follows
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  get 'account/follows', to: 'account_follows#index', as: 'account_follows' # my follows page

#NOTE
#reviews model made with scaffolding shortcut will need to run rails routes command in terminal to see specific routes
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id             :bigint           not null, primary key
#  body           :text
#  recipient_name :string
#  sender_name    :string
#  title          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  recipient_id   :integer
#  user_id        :bigint
#
class Message < ApplicationRecord
    validates :body, presence: true
    validates :sender_name, presence: true
    validates :title, presence: true
    validates :recipient_id, presence: true
    validates :recipient_name, presence: true

    has_many :my_notifications, dependent: :destroy
    has_rich_text :body #added for action text to send pictures and videos
end
    

app/controllers/messages_controller.rb
#Messages work like an email system and are populated in each user's own message index
#users can send messages with videos, and reply back to messages from options within a received message.
#you can send messages with options on a user's profile or on options on requests
class MessagesController < ApplicationController
    before_action :authenticate_user!
 

    def index
         messages = Message.all
         respond_to do |format|
             format.html { render :index, locals: { messages: messages } }
         end
     end

    def show
        message = Message.find(params[:id])
        respond_to do |format|
            format.html { render :show, locals: { message: message } }
        end
    end

     def new
        message = Message.new(params[:message])
         respond_to do |format|
             format.html { render :new, locals: { message: message } }
         end
     end
     
    def create
         # new object from params
         @message = Message.new(params.require(:message).permit(:body, :title, :recipient_name,:sender_name, :recipient_id))
         @message.sender_name = [current_user.first_name, current_user.last_name].join(' ')
         @message.user_id = current_user.id
                 # respond_to block
         respond_to do |format|
             format.html do
                 if @message.save
                    #Notifications enabled for messages
                    MyNotification.create(recipient_id: @message.recipient_id, actor: current_user, action: "New Message", notifiable: @message, message_id: @message.id)
                     # success message
                     flash[:success] = "Message sent successfully"
                     # redirect to index
                     redirect_to messages_url
                 else
                     # error message
                     flash.now[:error] = if Rails.env.development? 
                                            @message.errors.full_messages
                                        else
                                            "Error: Message could not be sent"
                                        end
                     # render new
                     render :new, locals: { message: @message }
                 end
             end
         end
       
     end

    def edit
        message = Message.find(params[:id])
        respond_to do |format|
            format.html { render :edit, locals: { message: message } }
        end
    end

    def update
        # load existing object again from URL param
        message = Message.find(params[:id])
        # respond_to block
        respond_to do |format|
            format.html do
                if message.update(params.require(:message).permit(:body, :title, :recipient_name,:sender_name, :recipient_id))
                    # success message
                    flash[:success] = 'Message updated successfully'
                    # redirect to index
                    redirect_to messages_url
                else
                    # error message
                    flash.now[:error] = 'Error: Message could not be updated'
                    # render edit
                    render :edit, locals: { message: message }
                end
            end
        end
    end

    def destroy
        # load existing object again from URL param
        message = Message.find(params[:id])
        message.destroy
        # respond_to block
        respond_to do |format|
            format.html do
                # success message
                flash[:success] = 'Message removed successfully'
                # redirect to index
                redirect_to messages_url
            end
        end
    end
end
class DemoController
    def index
      @some_variable = "dlroW olleH"
      @some_variable = backwards
    end
    private 
    def backwards
       @some_variable.reverse
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/edit.html.erb
<div id="page-contet">
<h1 class="text-center mt-4">Edit Messages</h1>
<%= form_with model: message, url: message_path, class: "shadow p-5 mb-10 bg-white", method: :patch, local: true, scope: :message do |f| %>
<% if current_user.try(:id)==message.user_id %>
  <div >
   <strong><label>Title</label></strong>
    <%= f.text_field :title, placeholder:'Hello',class: "form-control shadow" %>
   
  </div>
 <div>
  <strong><label>Message</label></strong>
    <%= f.rich_text_area :body, placeholder:'Say something...' %>
    
 </div>
<br>
<br>
  <div >     
  <%= f.submit "Update", :class => "btn btn-outline-warning" %>
</div>

  <% end %>
<% end %>

app/views/messages/index.html.erb
<h1 class="text-center">My Messages</h1>
<% messages.each do |message| %>
<% if current_user.try(:id)==message.recipient_id %> 
<div id="<%= dom_id(message) %>">
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-header font-italic">
  <div class="card text-center">
    <div class="card-header">
      Received Message From <%=message.sender_name if current_user %> <%# sender_name %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to message.title, message_path(message), class: "text-success"%></h5>
      <p class="card-text"><%= truncate(message.sender_name, lenght: 100) %></p>
      <%= link_to "View", message_path(message), class: "btn btn-outline-success" %>
      <%= link_to "Delete", message_path(message), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
   
    </div>
    <%# time in words %>
    <div class="card-footer text-muted">
      <small>Received <%= time_ago_in_words(message.created_at) %> ago </small>
    </div>
  </div>
  </div>
  </div>
  </div>
  </div>
<%end%>
<%end%>

<% messages.each do |message| %>
<% if current_user.try(:id)==message.user_id %>
  
  <div id="<%= dom_id(message) %>">

<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-header font-italic">
  <div class="card text-center">
    <div class="card-header">
      Sent Message to <%=message.recipient_name if current_user %> <%# recipient_name %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to message.title, message_path(message), class: "text-success"%></h5>
      <p class="card-text"><%= truncate(message.sender_name, lenght: 100) %></p>
      <%= link_to "View", message_path(message), class: "btn btn-outline-success" %>
     <%= link_to "Edit", edit_message_path(message),class: "btn btn-outline-info", method: :get %>
      <%= link_to "Delete", message_path(message), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
    <%# time in words %>
    <div class="card-footer text-muted">
     <small>Sent <%= time_ago_in_words(message.created_at) %> ago, 
            edited <%= time_ago_in_words(message.updated_at) %> ago</small>
    </div>
  </div>
  </div>
  </div>
  </div>
  </div>
<%end%>
<%end%>

app/views/messages/new.html.erb
<div id="page-contet">
<h1 class="text-center mt-4">New Messages</h1>
<%= form_with model: message, url: messages_path, class: "shadow p-5 mb-10 bg-white", method: :post, local: true, scope: :message do |f| %>
  <div>
  <strong><label>Title</label></strong>
    <%= f.text_field :title, placeholder:'Hello',class: "form-control shadow" %>
  </div>
  <%# rich text %>
  <div>
  <strong><label>Message</label></strong>
    <%= f.rich_text_area :body, placeholder:'Say something...' %>
    
 </div>
<%= f.hidden_field :recipient_id, :value => params[:recipient_id] %>
<%= f.hidden_field :recipient_name, :value => params[:recipient_name] %>
  <div > 
  <%= f.submit "Send Message", :class => "btn btn-outline-warning" %>
</div>
<% end %>

app/views/messages/show.html.erb
<%# Updated show page for videoJS imports %>
<link href="https://vjs.zencdn.net/7.8.3/video-js.css" rel="stylesheet" />
<div id="page-contet">
<h1 class="text-center mt-4">New Message</h1>
<div class="container card p-3 mb-2 bg-light text-dark">
 <div class = "text-center">
  <div class="card text-white bg-dark mb-5" style="max-width: 55rem;">
  
    <h2><%= message.sender_name%> to <%= message.recipient_name %></h2>
  </div>
  </div>
  <div class="card">
  
  <div class="card-body">
  
    <ul>
        <div class="form-group row">
        <label> <h5 class="card-title"> <%=message.title %> </label>
      </div>
       <div class="form-group row">
       <label> <p class="card-text"> <%=message.body%></p> <label> 
     </div>
     <div class="form-group row">
    
     <p><%= link_to 'Reply', new_message_path(:recipient_id => message.user_id, :recipient_name => message.sender_name), :class => "btn btn-outline-success" %></p>
     <p><%= link_to 'Back', messages_path, :class => "btn btn-outline-primary" %></p>
     <%= button_to 'Delete', message_path(message), method: :delete, :class => "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
      <script src="https://vjs.zencdn.net/7.8.3/video.js"></script> <%# for videos %>
     </div>
      </div>
       </div>
  
 </ul>
  