config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :users
  #root route
  root to: redirect('/home', status:302)

  #homepage
  get 'home', to: 'static_pages#home', as: 'home'
  get 'about', to: 'static_pages#about', as: 'about'

  # requests
  get 'requests', to: 'requests#index', as: 'requests' # index
  get 'requests/new', to: 'requests#new', as: 'new_request' # new
  post 'requests', to: 'requests#create' # create
  get 'requests/:id', to: 'requests#show', as: 'request' # show
  get 'requests/:id/edit', to: 'requests#edit', as: 'edit_request' # edit
  patch 'requests/:id', to: 'requests#update' # update (as needed)
  put 'requests/:id', to: 'requests#update' # update (full replacement)
  delete 'requests/:id', to: 'requests#destroy' # destroy

  # messages
  get 'messages', to: 'messages#index', as: 'messages' # index
  get 'messages/new', to: 'messages#new', as: 'new_message' # new
  post 'messages', to: 'messages#create' # create
  get 'messages/:id', to: 'messages#show', as: 'message' # show
  get 'messages/:id/edit', to: 'messages#edit', as: 'edit_message' # edit
  patch 'messages/:id', to: 'messages#update' # update (as needed)
  put 'messages/:id', to: 'messages#update' # update (full replacement)
  delete 'messages/:id', to: 'messages#destroy' # destroy


# globals
get 'globals', to: 'globals#index', as: 'globals' # index
get 'globals/new', to: 'globals#new', as: 'new_global' # new
post 'globals', to: 'globals#create' # create
get 'globals/:id', to: 'globals#show', as: 'global' # show
get 'globals/:id/edit', to: 'globals#edit', as: 'edit_global' # edit
patch 'globals/:id', to: 'globals#update' # update (as needed)
put 'globals/:id', to: 'globals#update' # update (full replacement)
delete 'globals/:id', to: 'globals#destroy' # destroy

#global_listings
get 'global_listings', to: 'global_listings#index', as: 'global_listings' # index
get 'global_listings/new', to: 'global_listings#new', as: 'new_global_global_listings' # new
post 'global_listings', to: 'global_listings#create' # create
get 'global_listings/:id', to: 'global_listings#show', as: 'global_listing' # show
get 'global_listings/:id/edit', to: 'global_listings#edit', as: 'edit_global_listing' # edit
patch 'global_listings/:id', to: 'global_listings#update' # update (as needed)
put 'global_listings/:id', to: 'global_listings#update' # update (full replacement)
delete 'global_listings/:id', to: 'global_listings#destroy' # destroy

  # users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'users/:id', to: 'users#show', as: 'user'

  get 'profile', to: 'static_pages#profile', as: 'profile'
  get 'users', to: 'users#index', as: 'users'

  

  # videos
  get 'account/videos', to: 'account_videos#index', as: 'account_videos' # index

  get 'account/videos/new', to: 'account_videos#new', as: 'new_account_video' # new
  post 'account/videos', to: 'account_videos#create' # create

  get '/videos/:id', to: 'videos#show', as: 'video' # show

  get 'videos/:id/edit', to: 'videos#edit', as: 'edit_video' #edit
  patch 'videos/:id', to: 'videos#update' # update
  put 'videos/:id', to: 'videos#update' # update

  delete 'videos/:id', to: 'videos#destroy' # delete


  #my_notifications
  resources :my_notifications do
    collection do 
      post :mark_as_read
    end
  end

  delete "my_notifications/:id", to: "my_notifications#destroy"  # delete
    
  # follows
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  get 'account/follows', to: 'account_follows#index', as: 'account_follows' # my follows page

#NOTE
#reviews model made with scaffolding shortcut will need to run rails routes command in terminal to see specific routes
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  bio                    :text
#  contact_info           :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  interests              :string
#  last_name              :string
#  major                  :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  teaching_methods       :string
#  volunteer_hours        :float
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         after_initialize :default_values
    
    def username
    return self.email.split('@')[0].capitalize
    end   
         private
           def default_values
             self.volunteer_hours||= 0.0

           end

 
  has_one_attached :avatar
   after_commit :add_default_avatar, on: %i[create update]
         
  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize: '150x150').processed
    else
      '/No_user.jpg'
    end
  end

  private
  def add_default_avatar
    unless avatar.attached?
      avatar.attach(
        io: File.open(
          Rails.root.join(
            'app', 'assets', 'images', 'No_user.jpg'
          )
        ), 
        filename: 'No_user.jpg',
        content_type: 'image/jpg'
      )
    end

   end


  def self.search(search)
    if search
      email = User.find_by(email: search)
      if email
        self.where(user_id: email)
      else
        @users = User.all 
      end
    else
      @users = User.all
    end
  end

  has_many(
    :videos,
    class_name: 'Video',
    foreign_key: 'user_id',
    inverse_of: :creator
  )

  # MyNotifications
  has_many :my_notifications, foreign_key: :recipient_id
 
  # Requests
  has_many :requests

  # Globals
  has_many :globals

  # Reviews
  has_many :reviews, dependent: :destroy

  # Given instance is the followed user
  # Calling "followers" returns the given instance's list of users that follow them
  has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow" # follows for given user instance
  has_many :followers, through: :received_follows, source: :follower               # users who follow given user intance

  # Given instance is the follower
  # Calling "following" returns the given instance's list of users they follow
  has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"         # follows a user gave someone else
  has_many :followings, through: :given_follows, source: :followed_user            # other users this user has followed

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index

        if params[:search].blank?
            @results = User.all
        else 
            @parameter = params[:search].downcase
            @results = User.all.where("lower(email) LIKE :search OR
                                       lower(first_name) LIKE :search OR
                                       lower(last_name) LIKE :search OR
                                       lower(interests) LIKE :search OR
                                       lower(major) LIKE :search", search: "%#{@parameter}%")               
        end
    end

    def show
        user = User.find(params[:id])
        respond_to do |format|
            format.html { render :show, locals: {user: user, videos: user.videos}}
        end
    end


    def follow
        # When a user is followed, they are added to the 'followings' list
        # On the other hand, the person giving the follow will be added to the opposite users 'followers' list

        user = User.find(params[:id])
        current_user.followings << user

        MyNotification.create(recipient_id: user.id, actor: current_user, action: "New Follow", notifiable: user, user_id: user.id)

        if current_user.followings.include?(user)
            flash[:success] = "Followed successfully"
        else 
            flash[:error] = "Could not follow successfully"
        end
        redirect_to user_path(user)
    end

    def unfollow
        # This function simply removes a user from the 'followings' list
        
        user = User.find(params[:id])
        current_user.followings.delete(user)

        if !current_user.followings.include?(user)
            flash[:success] = "Unfollowed successfully"
        else 
            flash[:error] = "Could not unfollow successfully"
        end
        redirect_to user_path(user)
    end

    def user_params
        params.require(:user).permit(:email, :first_name, :last_name, :bio, :search)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Find Tutors!</h1>

<%= form_tag users_path, :method => "get" do %>
<p>
    <%= text_field_tag :search, params[:search], placeholder: "Enter Names or Categories", class: "form-control" %>
    <%= submit_tag "Search", :email => nil %>
</p>
<% end %>

<div class="container">
    <div class ="row">

        <% @results.each do |user| %>
            <div class="card container border-dark mb-3" style ="width: 35rem">
                <div class="card-header row justify-content-between">
                <h4 class="card-title"><%= user.first_name%> <%= user.last_name%></h4>
                <div class="avatar">
                    <% if user.avatar.attached?%>
                        <img class="rounded-circle" height= "40" width="40" <%=image_tag(user.avatar)%>
                    <% end %>
                    </div>
                </div>
                        <div class="card-body">
                            <h5 class="card-subtitle mb-2 text-muted"><%= user.interests %></h5>
                            <p class="card-text"> <%= user.bio %></p>
                            <a href="#" class="card-link"><%= link_to 'Find Out More', user_path(user) %></a>
                        </div>
                </div>
            </div>
        </div>
            <% if user.videos.present?%>
            <% user.videos.each do |video| %>
                    <div class="card container border-primary mb-3" style ="width: 35rem">
                        <div class="card-header row ">
                            <h4>Video</h4>
                        </div>
                        <div class="card-body">
                                <h4 class="card-title"><%= link_to video.title, video_path(video)%></h4>
                                <h5 class="card-text"><%= video.description %></h5>
                        </div>      
                        <div class="card-footer text-muted">
                            <i>Made by <%= user.first_name%> <%= user.last_name%></i>
                        </div>                  
                    </div>
                <%end%>
            <%end%>

        <% end %>

    </div>
</div>

app/views/users/show.html.erb
<h1><%=user.first_name%> <%=user.last_name%></h1><br />

<% if user.avatar.attached? %>
  <%= image_tag((url_for(user.avatar)), style: 'display: block; margin: auto; width: 20%;')%>
<%end%>
<br>
<div class="card">
  <div class="card-header">
    <h5>About</h5>
  </div>
  <div class="card-body">
  <h6><%=user.bio%></h6>
    <ul>
        
        <li>Major: <%=user.major %> </li>
        <li>Interests: <%=user.interests %> </li>
        <li>Contact Information: <%=user.contact_info %> </li>
        <li>Email: <%=user.email %> </li>
        <li>Volunteer Hours: <%=user.volunteer_hours %> </li>
    </ul>
   <%# if not your profile then you can send message to the profile's owner or send a direct request to that user%>
   <%# upon clicking send message or direct request information is taken from the user profile's attributes to populate the new request or message attributes%>
    <% if user != current_user %>
      <%= link_to "Send Message", new_message_path(:recipient_id => user.id, :recipient_name => "#{user.first_name} #{ user.last_name}", class: "btn btn-primary"),:class => "btn btn-outline-primary"%>                                                                                                                                               
      <%= link_to "Direct Request", new_request_path(:recipient => user.id, :recipient_name => "#{user.first_name} #{ user.last_name}", class: "btn btn-primary"),:class => "btn btn-outline-primary" %>     
    <% else %>
      <%= link_to 'Personalize Profile', edit_user_registration_path, :class => "btn btn-outline-primary" %>
    <% end %>

  </div>
</div>


<br />
<br>

<h1><%=user.first_name%>'s Videos</h1>
<br>
<div align="center">
<% if user == current_user %>
    <%= link_to 'Add Video', new_account_video_path, :class => "btn btn-outline-primary" %>
    <br> 
  <% elsif current_user.followings.include?(user) %>
    <h6><i>You can unfollow a user to stop getting updates when they post videos.</i></h6>
    <br>
    <%= link_to "Unfollow", unfollow_user_path, method: "POST", :class => "btn btn-outline-primary" %> 
  <% else %>
    <h6><i>You can follow a user to get updates when they post videos!</i></h6>
    <br>
    <%= link_to "Follow", follow_user_path, method: "POST", :class => "btn btn-outline-primary" %>
    <br>
<% end %>
</div>

<br>

<% videos.each do |video| %>

  <div class="card container mb-3" style ="max-width: 40rem">
    <img class="card-img-top" src="<%= url_for(video.thumbnail, )%>" alt="Card image cap">
    <div class="card-footer">
      <h5>Title: <%= link_to video.title, video_path(video) %></h5>
      <h5 class="card-text">Description: <%= video.description%></h5>
    </div>
  </div>

  <br>

<% end %>

<br>