config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :users
  #root route
  root to: redirect('/home', status:302)

  #homepage
  get 'home', to: 'static_pages#home', as: 'home'
  get 'about', to: 'static_pages#about', as: 'about'

  # requests
  get 'requests', to: 'requests#index', as: 'requests' # index
  get 'requests/new', to: 'requests#new', as: 'new_request' # new
  post 'requests', to: 'requests#create' # create
  get 'requests/:id', to: 'requests#show', as: 'request' # show
  get 'requests/:id/edit', to: 'requests#edit', as: 'edit_request' # edit
  patch 'requests/:id', to: 'requests#update' # update (as needed)
  put 'requests/:id', to: 'requests#update' # update (full replacement)
  delete 'requests/:id', to: 'requests#destroy' # destroy

  # messages
  get 'messages', to: 'messages#index', as: 'messages' # index
  get 'messages/new', to: 'messages#new', as: 'new_message' # new
  post 'messages', to: 'messages#create' # create
  get 'messages/:id', to: 'messages#show', as: 'message' # show
  get 'messages/:id/edit', to: 'messages#edit', as: 'edit_message' # edit
  patch 'messages/:id', to: 'messages#update' # update (as needed)
  put 'messages/:id', to: 'messages#update' # update (full replacement)
  delete 'messages/:id', to: 'messages#destroy' # destroy


# globals
get 'globals', to: 'globals#index', as: 'globals' # index
get 'globals/new', to: 'globals#new', as: 'new_global' # new
post 'globals', to: 'globals#create' # create
get 'globals/:id', to: 'globals#show', as: 'global' # show
get 'globals/:id/edit', to: 'globals#edit', as: 'edit_global' # edit
patch 'globals/:id', to: 'globals#update' # update (as needed)
put 'globals/:id', to: 'globals#update' # update (full replacement)
delete 'globals/:id', to: 'globals#destroy' # destroy

#global_listings
get 'global_listings', to: 'global_listings#index', as: 'global_listings' # index
get 'global_listings/new', to: 'global_listings#new', as: 'new_global_global_listings' # new
post 'global_listings', to: 'global_listings#create' # create
get 'global_listings/:id', to: 'global_listings#show', as: 'global_listing' # show
get 'global_listings/:id/edit', to: 'global_listings#edit', as: 'edit_global_listing' # edit
patch 'global_listings/:id', to: 'global_listings#update' # update (as needed)
put 'global_listings/:id', to: 'global_listings#update' # update (full replacement)
delete 'global_listings/:id', to: 'global_listings#destroy' # destroy

  # users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'users/:id', to: 'users#show', as: 'user'

  get 'profile', to: 'static_pages#profile', as: 'profile'
  get 'users', to: 'users#index', as: 'users'

  

  # videos
  get 'account/videos', to: 'account_videos#index', as: 'account_videos' # index

  get 'account/videos/new', to: 'account_videos#new', as: 'new_account_video' # new
  post 'account/videos', to: 'account_videos#create' # create

  get '/videos/:id', to: 'videos#show', as: 'video' # show

  get 'videos/:id/edit', to: 'videos#edit', as: 'edit_video' #edit
  patch 'videos/:id', to: 'videos#update' # update
  put 'videos/:id', to: 'videos#update' # update

  delete 'videos/:id', to: 'videos#destroy' # delete


  #my_notifications
  resources :my_notifications do
    collection do 
      post :mark_as_read
    end
  end

  delete "my_notifications/:id", to: "my_notifications#destroy"  # delete
    
  # follows
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  get 'account/follows', to: 'account_follows#index', as: 'account_follows' # my follows page

#NOTE
#reviews model made with scaffolding shortcut will need to run rails routes command in terminal to see specific routes
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_videos_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Video < ApplicationRecord
    has_many :reviews
    has_one_attached :clip
    has_one_attached :thumbnail

    belongs_to(
        :creator,
        class_name: 'User',
        foreign_key: 'user_id',
        inverse_of: 'videos'
    )

    has_many :my_notifications, dependent: :destroy

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :require_permission, only: [:edit, :update, :destroy]


  def index
    @reviews = Review.all
    @videos = Video.all
  end


  def show
    @reviews = Review.all
  end

  def edit
  end

  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@video.creator), notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def require_permission
    video = Video.find(params[:id])
    if video.creator != current_user
      redirect_to video_path(video), flash: { error: "You do not have permission to do that." }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :description, :clip, :thumbnail)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video,  local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

   <div class="form-group">
    <%= form.label :clip %>
    <%= form.file_field :clip %>
  </div>

   <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit"Submit", :class => "btn btn-outline-info" %>
  </div>
  
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', video_path(@video) %>

app/views/videos/index.html.erb
<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Delete', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>
<style>
th, td {
  padding: 10px;
}
.hero-image4 {
  background-image: url("https://t4.ftcdn.net/jpg/02/33/43/27/240_F_233432777_dUvLZxOOxSgjJlLu8Zbx2rZgNw0EGZBk.jpg");
  background-color: #cccccc;
  height: 400px;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

.hero-text4 {
  text-align: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: white;
}
</style>

<!-- JSON video styling -->
<link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet" />

<!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
<script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>



<div align="center">
  <h2><%= @video.title %></h2>

    <video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="900"
    height="auto"
    poster="<%= url_for(@video.thumbnail)%>"
    data-setup="{}"
  >
    <source src="<%= url_for(@video.clip)%>" type="video/mp4" />

  </video>

  <h5 align="left">
  <br>
    <strong>Description:</strong>
    <%= @video.description %>
  </h5>

<script src="https://vjs.zencdn.net/7.8.4/video.js"></script>

  <br>
  
<%# Allows for reviews to show for each video--will loop through review objects and if review vkey attribute matches video id attribute will show object information below respective video%>

  <% @reviews.each do |review| %>
  
    <% if review.try(:vkey)==@video.id %>
      <div id="<%= dom_id(review) %>">
  
  <%# All reviews contain rating 1-5 integer and comment; integer rating will correspond with stars upon display%>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th>Reviewer Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
      <tr>
         <% if review.rating  == 1 %>
         <td>⭐</td>
         <%end%>
         <% if review.rating  == 2 %>
         <td>⭐⭐</td>
          <%end%>
         <% if review.rating  == 3 %>
         <td>⭐⭐⭐</td>
          <%end%>
         <% if review.rating  == 4 %>
         <td>⭐⭐⭐⭐</td>
          <%end%>
         <% if review.rating  == 5 %>
         <td>⭐⭐⭐⭐⭐</td>
          <%end%>
        <td><%= review.comment %></td>
        <td> <%=review.sender_name %></td>

      </tr>
       <div class="card-footer text-muted">
       <small>Received <%= time_ago_in_words(review.created_at) %> ago </small>
       <%if [current_user.first_name, current_user.last_name].join(' ') == review.sender_name%>
       <td><%= link_to 'Delete', review, class: "btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
       <%end%>
       
       </div>
       </div>

  </tbody>
</table>
<%end%>
<%end%>
<br>
<%# if its your video you can edit and delete it; if you are vistior you can review the video%>
  <% if current_user == @video.creator %>
    <%= link_to 'Edit', edit_video_path(@video) %> |
    <%= link_to 'Delete', video_path(@video), method: :delete %>
  <%else%>
  <%= link_to 'Review Video', new_review_path( :user_id => @video.user_id,:vkey => @video.id) %>
  
  <% end %>
</div>