config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :users
  #root route
  root to: redirect('/home', status:302)

  #homepage
  get 'home', to: 'static_pages#home', as: 'home'
  get 'about', to: 'static_pages#about', as: 'about'

  # requests
  get 'requests', to: 'requests#index', as: 'requests' # index
  get 'requests/new', to: 'requests#new', as: 'new_request' # new
  post 'requests', to: 'requests#create' # create
  get 'requests/:id', to: 'requests#show', as: 'request' # show
  get 'requests/:id/edit', to: 'requests#edit', as: 'edit_request' # edit
  patch 'requests/:id', to: 'requests#update' # update (as needed)
  put 'requests/:id', to: 'requests#update' # update (full replacement)
  delete 'requests/:id', to: 'requests#destroy' # destroy

  # messages
  get 'messages', to: 'messages#index', as: 'messages' # index
  get 'messages/new', to: 'messages#new', as: 'new_message' # new
  post 'messages', to: 'messages#create' # create
  get 'messages/:id', to: 'messages#show', as: 'message' # show
  get 'messages/:id/edit', to: 'messages#edit', as: 'edit_message' # edit
  patch 'messages/:id', to: 'messages#update' # update (as needed)
  put 'messages/:id', to: 'messages#update' # update (full replacement)
  delete 'messages/:id', to: 'messages#destroy' # destroy


# globals
get 'globals', to: 'globals#index', as: 'globals' # index
get 'globals/new', to: 'globals#new', as: 'new_global' # new
post 'globals', to: 'globals#create' # create
get 'globals/:id', to: 'globals#show', as: 'global' # show
get 'globals/:id/edit', to: 'globals#edit', as: 'edit_global' # edit
patch 'globals/:id', to: 'globals#update' # update (as needed)
put 'globals/:id', to: 'globals#update' # update (full replacement)
delete 'globals/:id', to: 'globals#destroy' # destroy

#global_listings
get 'global_listings', to: 'global_listings#index', as: 'global_listings' # index
get 'global_listings/new', to: 'global_listings#new', as: 'new_global_global_listings' # new
post 'global_listings', to: 'global_listings#create' # create
get 'global_listings/:id', to: 'global_listings#show', as: 'global_listing' # show
get 'global_listings/:id/edit', to: 'global_listings#edit', as: 'edit_global_listing' # edit
patch 'global_listings/:id', to: 'global_listings#update' # update (as needed)
put 'global_listings/:id', to: 'global_listings#update' # update (full replacement)
delete 'global_listings/:id', to: 'global_listings#destroy' # destroy

  # users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'users/:id', to: 'users#show', as: 'user'

  get 'profile', to: 'static_pages#profile', as: 'profile'
  get 'users', to: 'users#index', as: 'users'

  

  # videos
  get 'account/videos', to: 'account_videos#index', as: 'account_videos' # index

  get 'account/videos/new', to: 'account_videos#new', as: 'new_account_video' # new
  post 'account/videos', to: 'account_videos#create' # create

  get '/videos/:id', to: 'videos#show', as: 'video' # show

  get 'videos/:id/edit', to: 'videos#edit', as: 'edit_video' #edit
  patch 'videos/:id', to: 'videos#update' # update
  put 'videos/:id', to: 'videos#update' # update

  delete 'videos/:id', to: 'videos#destroy' # delete


  #my_notifications
  resources :my_notifications do
    collection do 
      post :mark_as_read
    end
  end

  delete "my_notifications/:id", to: "my_notifications#destroy"  # delete
    
  # follows
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  get 'account/follows', to: 'account_follows#index', as: 'account_follows' # my follows page

#NOTE
#reviews model made with scaffolding shortcut will need to run rails routes command in terminal to see specific routes
end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id                  :bigint           not null, primary key
#  acceptedFlag        :boolean
#  category            :string
#  completedFlag       :boolean
#  description         :string
#  learningPreference  :string
#  new_volunteer_hours :float
#  recipient           :integer
#  recipient_name      :string
#  sender              :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :bigint
#
# Indexes
#
#  index_requests_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Request < ApplicationRecord

    validates :description, presence: true
    validates :category, presence: true
    validates :learningPreference, presence: true
    validates :recipient, presence: true
    validates :sender, presence: true
    
    belongs_to :user

    has_many :my_notifications, dependent: :destroy
     
  end  

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
#The controller class for direct requests
#direct requests are requests from users made directly to another user
   before_action :authenticate_user!
   #global variable @@please_review allows for users to review their teachers upon closure of request
    @@please_review = 0


    def index
         requests = Request.all
         respond_to do |format|
             format.html { render :index, locals: { requests: requests } }
         end
     end

    def show
        request = Request.find(params[:id])
        respond_to do |format|
            format.html { render :show, locals: { request: request } }
        end
    end

     def new 
         request = Request.new(params[:request])
         respond_to do |format|
             format.html { render :new, locals: { request: request } }
         end
     end
    
    def create
         request = Request.new(params.require(:request).permit(:description, :category, :learningPreference, :recipient,:sender, :acceptedFlag, :completedFlag, :new_volunteer_hours, :recipient_name))
         # need to initialize some attributes upon creation of new request
         request.user_id = current_user.id
         request.acceptedFlag = false
         request.completedFlag = false
         request.sender = [current_user.first_name, current_user.last_name].join(' ')
         # respond_to block
         respond_to do |format|
             format.html do
                 if request.save
                    # notification enabled for request creation and updates of request (see below update method)
                    MyNotification.create(recipient_id: request.recipient, actor: current_user, action: "New Request", notifiable: request, request_id: request.id)
                     # success message
                     flash[:success] = "Request saved successfully"
                     # redirect to index
                     redirect_to requests_url
                 else
                     # error message
                     flash.now[:error] = "Error: Request could not be saved"
                     # render new
                     render :new, locals: { request: request }
                 end
             end
         end
       
     end

    def edit
        request = Request.find(params[:id])
        respond_to do |format|
            format.html { render :edit, locals: { request: request } }
        end
    end

    def update
        # load existing object again from URL param
        request = Request.find(params[:id])
        # respond_to block
        respond_to do |format|
            format.html do
                if request.update(params.require(:request).permit(:description, :category, :learningPreference, :recipient,:sender, :acceptedFlag, :completedFlag,:new_volunteer_hours))
                        if current_user.id == request.recipient
                        MyNotification.create(recipient_id: request.user_id, actor: current_user, action: "Updated Request", notifiable: request, request_id: request.id)
                        end
                        if current_user.id == request.user_id
                        MyNotification.create(recipient_id: request.recipient, actor: current_user, action: "Updated Request", notifiable: request, request_id: request.id)
                        end
                    
                    # success message
                    flash[:success] = 'Request updated successfully'
                    # redirect to index
                    redirect_to requests_url
                else
                    # error message
                    flash.now[:error] = 'Error: Request could not be updated'
                    # render edit
                    render :edit, locals: { request: request }
                end
            end
        end
    end

    def destroy
        # load existing object again from URL param
        request = Request.find(params[:id])
        # allows for student to review teacher per request destroy
        @@please_review = request.recipient
        if current_user.try(:id)==request.user_id
        if request.completedFlag == true
            #volunteer hours rewarded if request has been marked as completed by the teacher
            user = User.find(request.recipient)
            user.volunteer_hours += request.new_volunteer_hours
            user.save
        
        end
    end
        request.destroy
        # respond_to block
        respond_to do |format|
            format.html do
                # success message
                flash[:success] = 'Request removed successfully'
                # redirect to index
                redirect_to new_review_path(:user_id => @@please_review)
              
            end
        end
    end
end

class DemoController
    def index
      @some_variable = "dlroW olleH"
      @some_variable = backwards
    end
    private 
    def backwards
       @some_variable.reverse
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
   
end

app/views/requests/edit.html.erb
<%# Allows for updating of direct request, view depends upon whether current user is teacher or student%>

<h1 class="text-center">
Edit Request
</h1>


<%= form_with model: request, url: request_path, method: :patch, local: true, scope: :request do |f| %>
<% if current_user.try(:id)==request.user_id %>
  <div>
    <h5>Description of Your Request</h5>
    <%= f.text_field :description %>
  </div>
<br>
<br>
  
   <div class="form-group">
    <h5><%= f.label :category, "Category" %></h5>
    <%= f.text_field :category, placeholder: "Ex. Art, Science, Music" %>
  </div>
 

<br>
<br>
  
   <div class="form-group">
    <h5><%= f.label :learningPreference, "Learning Preference" %></h5>

    <%= f.radio_button :learningPreference, "Prerecorded Video"%> Prerecorded Video<br />

    <%= f.radio_button :learningPreference, "Live Zoom Meeting"%> Live Zoom Meeting<br />
    
    <%= f.radio_button :learningPreference, "1-in-1 in Person"%> 1-in-1 in Person<br />
  </div>

<br>
<br>


<div>
    <h5>How many hours do you think this teacher will need to complete the task requested?</h5>
 <%= f.text_field :new_volunteer_hours%>
    
  </div>

     

<%end%>



<% if current_user.try(:id)==request.recipient %>
  <div>
    <h5>Accept Request?</h5>
     <%= f.radio_button "acceptedFlag",  true %>
     <%= label_tag "acceptedFlag", 'Accept Request' %>
    <%= f.radio_button "acceptedFlag", false %>
     <%= label_tag "acceptedFlag", 'Decline Request' %>
  </div>
  
  <div>
    <h5>Completed Request?</h5>
      <%= f.radio_button "completedFlag",true %>
     <%= label_tag "completedFlag", 'Complete Request' %>
    <%= f.radio_button "completedFlag", false %>
     <%= label_tag "completedFlag", 'Request Not Completed' %>
  </div>


  <%end%>
  <br>
  <%= f.submit "Update Request", :class => "btn btn-outline-info" %>

<% end %>

app/views/requests/index.html.erb
<%# Index for direct requests--a personal listing for each user%>
<%# Allows for style formatting and picture decorations off of jpg%>
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.hero-image {
  background-image: url("https://image.freepik.com/free-photo/close-up-students-writing-reading-exam-answer-sheets-exercises-classroom-school-with-stress_73622-858.jpg");
  background-color: #cccccc;
  height: 200px;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

.hero-text {
  text-align: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: white;
}
.hero-image2 {
  background-image: url("https://image.freepik.com/free-photo/business-women-signature-document_1388-90.jpg");
  background-color: #cccccc;
  height: 200px;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

.hero-text2 {
  text-align: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: white;
}
</style>
</head>



<div class="big_header">
            <h1 class="blue" style="color:#2196F3;">My Direct Requests</h1>
            
        </div>
        
<br>
<div class = "padding">



<p class="text-info"><strong>You can send a request to another student by searching for them on the  homepage and clicking "Direct Request" on their profile!</strong></p>
<br>
<p class="text-info"><strong>If you want a closer look at your requests, click "See Request".</strong></p>
</div>
<div class="hero-image">
  <div class="hero-text">
    <h1 style="font-size:50px">My Sent Requests</h1>
  </div>
</div>

<br>
<%# loop through all requests and display based upon attribute status%>
<% requests.each do |request| %>

    <% if current_user.try(:id)==request.user_id %>
      <div id="<%= dom_id(request) %>">
      
    
    <% if request.acceptedFlag == true%>
<div class="container card p-1 mb-1 bg-success text-dark">
<%end%>
<% if request.acceptedFlag == false%>
<div class="container card p-1 mb-1 bg-danger text-dark">
<%end%>
 <div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a><%=link_to 'Teacher Profile', user_path(request.recipient), class: 'nav-link' %></a>
      </li>
      <li class="nav-item">
        <a><%= link_to 'See Request', request_path(request), class: 'nav-link' %></a>
      </li>
     
        <% if request.recipient != current_user.id %>
         <li class="nav-item">
    <%= link_to "Send Message", new_message_path(:recipient_id => request.recipient, :recipient_name => request.recipient_name, class: "btn btn-primary"), class: 'nav-link'  %>                                                                                                                                    
      </li>
      <%end%>
    </ul>
  </div>
    <div class="card-body">
    <h5 class="card-title">You sent a request to <%=request.recipient_name%>!</h5>
    <p class="card-text"><%= request.description%></p>
    
 
    <br>
     <div class="card-footer text-muted">
     <div class = "text-left">
     <% if request.acceptedFlag == true%>
           <p style="color:green;"><strong>Accepted by <%= request.recipient_name%>  ✔</strong></p>
            <%end%>
    <% if request.acceptedFlag == false%>
        <p style="color:red;"><strong>Not yet accepted ❌</strong></p>
        
            <%end%>
    
     <small>Sent <%= time_ago_in_words(request.created_at) %> ago, 
            edited <%= time_ago_in_words(request.updated_at) %> ago</small>
    </div>
  </div>
</div>
</div>
</div>
  <% end %>

<%end %>

<br>
<div class="hero-image2">
  <div class="hero-text2">
    <h1 style="font-size:50px">My Recieved Requests</h1>
  </div>
</div>
<br>
<% requests.each do |request| %> 

      <% if current_user.try(:id)==request.recipient %>
        <div id="<%= dom_id(request) %>">
        

<div class = "padding">
<% if request.acceptedFlag == true%>
<div class="container card p-1 mb-1 bg-success text-dark">
<%end%>
<% if request.acceptedFlag == false%>
<div class="container card p-1 mb-1 bg-danger text-dark">
<%end%>
 <div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a><%=link_to 'Student Profile', user_path(request.user_id), class: 'nav-link' %></a>
      </li>
      <li class="nav-item">
        <a><%= link_to 'See Request', request_path(request), class: 'nav-link' %></a>
      </li>
     
        <% if request.user_id != current_user.id %>
         <li class="nav-item">
    <%= link_to "Send Message", new_message_path(:recipient_id => request.user_id, :recipient_name => request.sender, class: "btn btn-primary"), class: 'nav-link'  %>                                                                                                                                    
      </li>
      <%end%>
    </ul>
  </div>
    <div class="card-body">
    <h5 class="card-title"><%=request.sender%> has asked you for help!</h5>
    <p class="card-text"><%= request.description%></p>
    
 
    <br>
     <div class="card-footer text-muted">
     <div class = "text-left">
     <% if request.acceptedFlag == true%>
        <p style="color:green;"><strong>Accepted by <%= request.recipient_name%>  ✔</strong></p>
            <%end%>
    <% if request.acceptedFlag == false%>
      <p style="color:red;"><strong>Not yet accepted ❌</strong></p>
            <%end%>
    
     <small>Sent <%= time_ago_in_words(request.created_at) %> ago, 
            edited <%= time_ago_in_words(request.updated_at) %> ago</small>
    </div>
  </div>
</div>
</div>
</div>
<%end%>
<%end%>


        
          

app/views/requests/new.html.erb
<%# When a user wants to make a direct request to another user this form will populate allowing for creation of new request%>

<h1 class="text-center">
New Request
</h1>

<%= form_with model: request, url: requests_path, method: :post, local: true, scope: :request do |f| %>

  <div>
    <h5>Description of Your Request</h5>
    <%= f.text_field :description %>
  </div>
<br>
<br>

   <div class="form-group">
    <h5><%= f.label :category, "Category" %></h5>
    <%= f.text_field :category, placeholder: "Ex. Art, Science, Music" %>
  </div>


<br>
<br>

    <div class="form-group">
      <h5><%= f.label :learningPreference, "Learning Preference" %></h5>

      <%= f.radio_button :learningPreference, "Prerecorded Video"%> Prerecorded Video<br />

      <%= f.radio_button :learningPreference, "Live Zoom Meeting"%> Live Zoom Meeting<br />
      
      <%= f.radio_button :learningPreference, "1-in-1 in Person"%> 1-in-1 in Person<br />
    </div>


<br>
<br>
<div>
    <h5>How many hours do you think this teacher will need to complete the task requested?</h5>
 <%= f.text_field :new_volunteer_hours%>
    
  </div>
  <br>

<%= f.hidden_field :recipient, :value => params[:recipient] %>
<%= f.hidden_field :recipient_name, :value => params[:recipient_name] %>
<%= f.submit "Send Request" %>

<% end %>

app/views/requests/show.html.erb
<%# A show page for each direct request. Will allow users to update fields depending on user status to request.%>

<br>
<div class="card border-info  p-3 mb-3 bg-light text-dark">
  
  <div class="card-header bg-transparent border-info text-center text-info">
    <h2>Request: <br> <%= request.sender%> to <%= request.recipient_name %></h2>
  </div>
  <div class="card-body text-info">
    <ul class="list-group list-group-flush ">
      <li class="list-group-item border-info bg-transparent">
        <h3 style="text-align:center;">General Information</h3>
        <br>
        <h5>  <u>Description:</u> <%= request.description%><h5>
        <h5>  <u>Category:</u> <%= request.category%><h5>
        <h5>  <u>Sender:</u> <%= request.sender%><h5>
        <h5>  <u>Recipient:</u> <%= request.recipient_name %><h5>
        <h5>  <u>Learning Preference:</u> <%= request.learningPreference %><h5>
        <h5>  <u>Volunteer Hours:</u> <%= request.new_volunteer_hours %><h5>
      </li>

      <li class="list-group-item border-info bg-transparent">
        <h3 style="text-align:center;">Active Status:</h3>
        <br>
          <%  if request.try(:acceptedFlag?)==true %>
            <h5><i class="card-text text-success">  <%= request.recipient_name %> has accepted this request!</i></h5>
          <% else %>
            <h5><i class="card-text text-danger"> <%= request.recipient_name %> has not yet accepted the request!</i></h5>
          <%end%>
          <br>
          <% if request.try(:completedFlag?)==true %>
            <h5><i class="card-text text-success"> This request has been completed and is waiting for <%= request.sender%> to close out the request!</i></h5>
          <% else %>
            <h5><i class="card-text text-danger"> <%= request.recipient_name %> has yet to complete the request!</i></h5>
          <%end%>
      </li>
    </ul>

    <br>
    <% if current_user.try(:id)==request.recipient %>
      <p class="card-text"><strong>Last Updated On: <%=request.updated_at%></strong></p>
      <%= link_to 'Edit Request Active Status', edit_request_path(request), method: :get, :class => "btn btn-info text-center" %>
    <% else %>
      <p><%= link_to 'Edit Request General Information', edit_request_path(request), method: :get, :class => "btn btn-info text-center"  %></p>
      
     <p><%= button_to 'Close Out Request and Review Teacher', request_path(request), method: :delete,  :class => "btn btn-info text-center"  %></p>
    <p><b>Warning: Volunteer hours only rewarded if teacher has marked the request as completed!.</b> <p>
    
    <%end%>
    
  </div>
</div> 

    
   
    